### PR TITLE
要做诚实的好孩子 :-1:

### PR DESCRIPTION
**Pull request by zhangjingye03**
撒谎会遭天谴的

### CODE REVIEW

**Comment by GhostShadowTan** [comment]
失误，致歉。。。看简介你是团委的小伙伴吗，你好。。。再次致歉，谢谢纠正

**Comment by zhangjingye03** [comment]
我不喜欢带有政治色彩，不用叫我团委的，我只是兼职帮他们写点代码的 :joy: 
看好你们的后台，加油↖(^ω^)↗

**Comment by yyl99311** [comment]
Sorry, it's a private project We don't accept commit. Thank you for your support.

**Comment by zhangjingye03** [comment]
You're **naive**, my friend. We gotta keep our focus.

**Comment by yyl99311** [comment]
Your suggestions will be welcomed. We would make contact with you if we had decided to take any of your advice.

**Comment by zhangjingye03** [comment]
# You are really **fool**
Why did you make a decision to open source?
It's to **gather others' view** on your project.
If you want to open source *privately*, that doesn't make amy sense.

**Comment by yyl99311** [comment]
We made the project open source in order to permit others having a glance on them and obtain some great advice from other guys.

**Comment by GhostShadowTan** [comment]
别在这里聊天！天天收邮件十分烦躁！

**Comment by df7c5117** [comment]
notification has boooooooooooomed #滑稽

**Comment by JerryLoveZhiXin** [comment]
……zhangjingye学长你好逗……对了我开了个pull request 快去看看看

**Pull request closed without merging**
